package com.vf.uk.dal.broadband.inventory.entity;

/*
 * Delivery Method API
 * gives the delivery methods related to the basket or sku id's
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import java.util.List;

/**
 * Each delivery object represents a delivery method.
 */ 
public class DeliveryMethods {
	
	/** The product id. */
	private String productId = null;

	/** The display name. */
	private String displayName = null;

	/** The delivery type. */
	private String deliveryType = null;

	/** The stock status. */
	private String stockStatus = null;

	/** The price. */
	private DeliveryPrice price = null;

	/** The delivery method. */
	private String deliveryMethod = null;

	/** The description. */
	private String description = null;

	/** The partner. */
	private String partner = null;

	/** The available time. */
	private String availableTime = null;

	/** The cut off time. */
	private String cutOffTime = null;

	/** The packaging date. */
	private String packagingDate = null;

	/** The back order product names. */
	private List<String> backOrderProductNames = null;

	/** The out of stock product names. */
	private List<String> outOfStockProductNames = null;

	/**
	 * Product id.
	 *
	 * @param productId the product id
	 * @return the delivery methods
	 */
	public DeliveryMethods productId(String productId) {
		this.productId = productId;
		return this;
	}

	/**
	 * This is the external id of the delivery product. Unique for each delviery method
	 * @return skuId
	 **/
	public String getProductId() {
		return productId;
	}

	/**
	 * Sets the product id.
	 *
	 * @param productId the new product id
	 */
	public void setProductId(String productId) {
		this.productId = productId;
	}

	/**
	 * Display name.
	 *
	 * @param displayName the display name
	 * @return the delivery methods
	 */
	public DeliveryMethods displayName(String displayName) {
		this.displayName = displayName;
		return this;
	}

	/**
	 * Display name of the delivery.
	 *
	 * @return displayName
	 */
	public String getDisplayName() {
		return displayName;
	}

	/**
	 * Sets the display name.
	 *
	 * @param displayName the new display name
	 */
	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	/**
	 * Delivery type.
	 *
	 * @param deliveryType the delivery type
	 * @return the delivery methods
	 */
	public DeliveryMethods deliveryType(String deliveryType) {
		this.deliveryType = deliveryType;
		return this;
	}

	/**
	 * Type of the delivery. Consists of standard, premium or clickAndCollect
	 * @return deliveryType
	 **/
	public String getDeliveryType() {
		return deliveryType;
	}

	/**
	 * Sets the delivery type.
	 *
	 * @param deliveryType the new delivery type
	 */
	public void setDeliveryType(String deliveryType) {
		this.deliveryType = deliveryType;
	}

	/**
	 * Stock status.
	 *
	 * @param stockStatus the stock status
	 * @return the delivery methods
	 */
	public DeliveryMethods stockStatus(String stockStatus) {
		this.stockStatus = stockStatus;
		return this;
	}

	/**
	 * Four possible values InStock,outOfStock,preOrder,backorder.
	 *
	 * @return stockStatus
	 */
	public String getStockStatus() {
		return stockStatus;
	}

	/**
	 * Sets the stock status.
	 *
	 * @param stockStatus the new stock status
	 */
	public void setStockStatus(String stockStatus) {
		this.stockStatus = stockStatus;
	}

	/**
	 * Price.
	 *
	 * @param price the price
	 * @return the delivery methods
	 */
	public DeliveryMethods price(DeliveryPrice price) {
		this.price = price;
		return this;
	}

	/**
	 * Prices associated with the delivery method. Applicable for premium delivery options
	 * @return price
	 **/
	public DeliveryPrice getPrice() {
		return price;
	}

	/**
	 * Sets the price.
	 *
	 * @param price the new price
	 */
	public void setPrice(DeliveryPrice price) {
		this.price = price;
	}

	/**
	 * Delivery method.
	 *
	 * @param deliveryMethod the delivery method
	 * @return the delivery methods
	 */
	public DeliveryMethods deliveryMethod(String deliveryMethod) {
		this.deliveryMethod = deliveryMethod;
		return this;
	}

	/**
	 * Delivery Method of the delivery options like WK86 etc.
	 * @return deliveryMethod
	 **/
	public String getDeliveryMethod() {
		return deliveryMethod;
	}

	/**
	 * Sets the delivery method.
	 *
	 * @param deliveryMethod the new delivery method
	 */
	public void setDeliveryMethod(String deliveryMethod) {
		this.deliveryMethod = deliveryMethod;
	}

	/**
	 * Description.
	 *
	 * @param description the description
	 * @return the delivery methods
	 */
	public DeliveryMethods description(String description) {
		this.description = description;
		return this;
	}

	/**
	 * Additional information to the calling application to identify the delivery category.list of values : Standard/Premium/store
	 * @return description
	 **/
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Partner.
	 *
	 * @param partner the partner
	 * @return the delivery methods
	 */
	public DeliveryMethods partner(String partner) {
		this.partner = partner;
		return this;
	}

	/**
	 * Additional information to the calling application to identify the delivery partner. DPD/RoyalMail.
	 * @return partner
	 **/
	public String getPartner() {
		return partner;
	}

	/**
	 * Sets the partner.
	 *
	 * @param partner the new partner
	 */
	public void setPartner(String partner) {
		this.partner = partner;
	}

	/**
	 * Available time.
	 *
	 * @param availableTime the available time
	 * @return the delivery methods
	 */
	public DeliveryMethods availableTime(String availableTime) {
		this.availableTime = availableTime;
		return this;
	}

	/**
	 * available time calculated based on stock availability for standard/premium delivery. For stores, available time will be NULL as it is calculated by other service
	 * @return availableTime
	 **/
	public String getAvailableTime() {
		return availableTime;
	}

	/**
	 * Sets the available time.
	 *
	 * @param availableTime the new available time
	 */
	public void setAvailableTime(String availableTime) {
		this.availableTime = availableTime;
	}

	/**
	 * Cut off time.
	 *
	 * @param cutOffTime the cut off time
	 * @return the delivery methods
	 */
	public DeliveryMethods cutOffTime(String cutOffTime) {
		this.cutOffTime = cutOffTime;
		return this;
	}

	/**
	 * to be sent to the client for displaying the messages based on teh cut off time in the frontend.
	 *
	 * @return cutOffTime
	 */
	public String getCutOffTime() {
		return cutOffTime;
	}

	/**
	 * Gets the out of stock product names.
	 *
	 * @return the out of stock product names
	 */
	public List<String> getOutOfStockProductNames() {
		return outOfStockProductNames;
	}

	/**
	 * Sets the out of stock product names.
	 *
	 * @param outOfStockProductNames the new out of stock product names
	 */
	public void setOutOfStockProductNames(List<String> outOfStockProductNames) {
		this.outOfStockProductNames = outOfStockProductNames;
	}

	/**
	 * Sets the cut off time.
	 *
	 * @param cutOffTime the new cut off time
	 */
	public void setCutOffTime(String cutOffTime) {
		this.cutOffTime = cutOffTime;
	}

	/**
	 * Packaging date.
	 *
	 * @param packagingDate the packaging date
	 * @return the delivery methods
	 */
	public DeliveryMethods packagingDate(String packagingDate) {
		this.packagingDate = packagingDate;
		return this;
	}

	/**
	 * value will be true if the order is placed before cut off and false after cut off.
	 *
	 * @return beforeCutOffTime
	 */
	public String getPackagingDate() {
		return packagingDate;
	}

	/**
	 * Sets the packaging date.
	 *
	 * @param packagingDate the new packaging date
	 */
	public void setPackagingDate(String packagingDate) {
		this.packagingDate = packagingDate;
	}

	/**
	 * Back order product names.
	 *
	 * @param backOrderProductNames the back order product names
	 * @return the delivery methods
	 */
	public DeliveryMethods backOrderProductNames(List<String> backOrderProductNames) {
		this.backOrderProductNames = backOrderProductNames;
		return this;
	}

	/**
	 * Holds List of services executed for the journey.
	 *
	 * @return slowMovingProductsName
	 */
	public List<String> getBackOrderProductNames() {
		return backOrderProductNames;
	}

	/**
	 * Sets the back order product names.
	 *
	 * @param backOrderProductNames the new back order product names
	 */
	public void setBackOrderProductNames(List<String> backOrderProductNames) {
		this.backOrderProductNames = backOrderProductNames;
	}
}


