package com.vf.uk.dal.broadband.inventory.entity;

/*
 * Delivery Method API
 * gives the delivery methods related to the basket or sku id's
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import java.util.List;

/**
 * Each delivery object represents a delivery method.
 */ 
public class DeliveryMethods {
	private String productId = null;

	private String displayName = null;

	private String deliveryType = null;

	private String stockStatus = null;

	private DeliveryPrice price = null;

	private String deliveryMethod = null;

	private String description = null;

	private String partner = null;

	private String availableTime = null;

	private String cutOffTime = null;

	private String packagingDate = null;

	private List<String> backOrderProductNames = null;

	private List<String> outOfStockProductNames = null;

	/**
	 * @param skuId
	 * @return
	 */
	public DeliveryMethods productId(String productId) {
		this.productId = productId;
		return this;
	}

	/**
	 * This is the external id of the delivery product. Unique for each delviery method
	 * @return skuId
	 **/
	public String getProductId() {
		return productId;
	}

	/**
	 * @param skuId
	 */
	public void setProductId(String productId) {
		this.productId = productId;
	}

	/**
	 * @param displayName
	 * @return
	 */
	public DeliveryMethods displayName(String displayName) {
		this.displayName = displayName;
		return this;
	}

	/**
	 * Display name of the delivery
	 * @return displayName
	 **/
	public String getDisplayName() {
		return displayName;
	}

	/**
	 * @param displayName
	 */
	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	/**
	 * @param deliveryType
	 * @return
	 */
	public DeliveryMethods deliveryType(String deliveryType) {
		this.deliveryType = deliveryType;
		return this;
	}

	/**
	 * Type of the delivery. Consists of standard, premium or clickAndCollect
	 * @return deliveryType
	 **/
	public String getDeliveryType() {
		return deliveryType;
	}

	/**
	 * @param deliveryType
	 */
	public void setDeliveryType(String deliveryType) {
		this.deliveryType = deliveryType;
	}

	/**
	 * @param stockStatus
	 * @return
	 */
	public DeliveryMethods stockStatus(String stockStatus) {
		this.stockStatus = stockStatus;
		return this;
	}

	/**
	 * Four possible values InStock,outOfStock,preOrder,backorder
	 * @return stockStatus
	 **/
	public String getStockStatus() {
		return stockStatus;
	}

	/**
	 * @param stockStatus
	 */
	public void setStockStatus(String stockStatus) {
		this.stockStatus = stockStatus;
	}

	/**
	 * @param price
	 * @return
	 */
	public DeliveryMethods price(DeliveryPrice price) {
		this.price = price;
		return this;
	}

	/**
	 * Prices associated with the delivery method. Applicable for premium delivery options
	 * @return price
	 **/
	public DeliveryPrice getPrice() {
		return price;
	}

	/**
	 * @param price
	 */
	public void setPrice(DeliveryPrice price) {
		this.price = price;
	}

	/**
	 * @param deliveryMethod
	 * @return
	 */
	public DeliveryMethods deliveryMethod(String deliveryMethod) {
		this.deliveryMethod = deliveryMethod;
		return this;
	}

	/**
	 * Delivery Method of the delivery options like WK86 etc.
	 * @return deliveryMethod
	 **/
	public String getDeliveryMethod() {
		return deliveryMethod;
	}

	/**
	 * @param deliveryMethod
	 */
	public void setDeliveryMethod(String deliveryMethod) {
		this.deliveryMethod = deliveryMethod;
	}

	/**
	 * @param description
	 * @return
	 */
	public DeliveryMethods description(String description) {
		this.description = description;
		return this;
	}

	/**
	 * Additional information to the calling application to identify the delivery category.list of values : Standard/Premium/store
	 * @return description
	 **/
	public String getDescription() {
		return description;
	}

	/**
	 * @param description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @param partner
	 * @return
	 */
	public DeliveryMethods partner(String partner) {
		this.partner = partner;
		return this;
	}

	/**
	 * Additional information to the calling application to identify the delivery partner. DPD/RoyalMail.
	 * @return partner
	 **/
	public String getPartner() {
		return partner;
	}

	/**
	 * @param partner
	 */
	public void setPartner(String partner) {
		this.partner = partner;
	}

	/**
	 * @param availableTime
	 * @return
	 */
	public DeliveryMethods availableTime(String availableTime) {
		this.availableTime = availableTime;
		return this;
	}

	/**
	 * available time calculated based on stock availability for standard/premium delivery. For stores, available time will be NULL as it is calculated by other service
	 * @return availableTime
	 **/
	public String getAvailableTime() {
		return availableTime;
	}

	/**
	 * @param availableTime
	 */
	public void setAvailableTime(String availableTime) {
		this.availableTime = availableTime;
	}

	/**
	 * @param cutOffTime
	 * @return
	 */
	public DeliveryMethods cutOffTime(String cutOffTime) {
		this.cutOffTime = cutOffTime;
		return this;
	}

	/**
	 * to be sent to the client for displaying the messages based on teh cut off time in the frontend
	 * @return cutOffTime
	 **/
	public String getCutOffTime() {
		return cutOffTime;
	}

	/**
	 * @return
	 */
	public List<String> getOutOfStockProductNames() {
		return outOfStockProductNames;
	}

	/**
	 * @param outOfStockProductNames
	 */
	public void setOutOfStockProductNames(List<String> outOfStockProductNames) {
		this.outOfStockProductNames = outOfStockProductNames;
	}

	/**
	 * @param cutOffTime
	 */
	public void setCutOffTime(String cutOffTime) {
		this.cutOffTime = cutOffTime;
	}

	/**
	 * @param packagingDate
	 * @return
	 */
	public DeliveryMethods packagingDate(String packagingDate) {
		this.packagingDate = packagingDate;
		return this;
	}

	/**
	 * value will be true if the order is placed before cut off and false after cut off
	 * @return beforeCutOffTime
	 **/
	public String getPackagingDate() {
		return packagingDate;
	}

	/**
	 * @param packagingDate
	 */
	public void setPackagingDate(String packagingDate) {
		this.packagingDate = packagingDate;
	}

	/**
	 * @param backOrderProductNames
	 * @return
	 */
	public DeliveryMethods backOrderProductNames(List<String> backOrderProductNames) {
		this.backOrderProductNames = backOrderProductNames;
		return this;
	}

	/**
	 * Holds List of services executed for the journey
	 * @return slowMovingProductsName
	 **/
	public List<String> getBackOrderProductNames() {
		return backOrderProductNames;
	}

	/**
	 * @param backOrderProductNames
	 */
	public void setBackOrderProductNames(List<String> backOrderProductNames) {
		this.backOrderProductNames = backOrderProductNames;
	}
}


