/*
 * Journey APIs
 * Journey APIs for Authenticated Journeys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.broadband.cache.repository.entity;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;

/**
 * AppointmentWindow.
 */
@Data
public class AppointmentWindow implements Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = -668687293347074917L;

	/** The identification id. */
	@JsonProperty("identificationId")
	private String identificationId = null;

	/** The start date time. */
	@JsonProperty("startDateTime")
	private String startDateTime = null;

	/** The operational preference code. */
	@JsonProperty("operationalPreferenceCode")
	private String operationalPreferenceCode = null;

	/** The time slot. */
	@JsonProperty("timeSlot")
	private String timeSlot = null;

}
