/*
 * Journey APIs
 * Journey APIs for Authenticated Journeys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.broadband.cache.repository.entity;

import lombok.Data;

/**
 * SalesOrderAppointmentRequest
 */
@Data
public class SalesOrderAppointmentRequest {
	private AppointmentWindow appointmentWindow = null;

	private SiteNote siteNote = null;

}
