package com.vf.uk.dal.broadband.entity.customer;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;

/**
 * The Class BankAccountDetails.
 */
@Data
public class BankAccountDetails {

	/**
	 * mandateId -GCPL The unique ID generated by the CRM System for a Direct
	 * Debit mandate. e.g. 1-15ECS
	 */
	@JsonProperty("mandateId")
	private String mandateId;

	/** bankAccountNumber -GCPL. */
	@JsonProperty("bankAccountNumber")
	private String bankAccountNumber;

	/**
	 * bankAccountName -GCPL Name of the bank account owned by this customer
	 * account. e.g. William Wallace
	 */
	@JsonProperty("bankAccountName")
	private String bankAccountName;

	/**
	 * typeCode -GCPL Account Type. Examples are Checking, Savings etc
	 */
	@JsonProperty("typeCode")
	private String typeCode;

	/**
	 * bankBranchReference -GCPL Customer bank account bank branch. A branch of
	 * a bank is a retail location that provides banking services
	 */
	@JsonProperty("bankBranchReference")
	private String bankBranchReference;

	/**
	 * preferredLanguageCode -GCPL Preferred language of communication with the
	 * person or department that acts as a point of contact for the banking
	 * institution of the customer bank account.
	 */
	@JsonProperty("preferredLanguageCode")
	private String preferredLanguageCode;

	/**
	 * organizationName -GCPL Name of the banking institution of the customer
	 * bank account.
	 */
	@JsonProperty("organizationName")
	private String organizationName;

	/** routingNumber -GCPL Sort code of the banking institution. */
	@JsonProperty("routingNumber")
	private String routingNumber;

	/**
	 * description -GCPL Bank account name used to link the Bank Account to
	 * Payment Profile and Billing Profile accordingly: they have the same name
	 * e.f William Wallace Billing Profile
	 */
	@JsonProperty("description")
	private String description;

}
