package com.vf.uk.dal.broadband.entity.customer;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;

/**
 * The Class CreditVet.
 */
@Data
public class CreditVet {


	/**
	 * creditVetId -GCPL corresponds to Identification/ApplicactionObjectKey/ID.
	 * Unique reference number generated by the CreditVet application for the
	 * Standalone CreditVet request. e.g. 45129438
	 */
	@JsonProperty("creditVetId")
	private String creditVetId;

	/**
	 * outcome -GCPL Outcome of credit vet decision which will indicate if the
	 * Credit Vet request is acceptable, declined, requires additional information
	 * or has been refered to a Risk Assesment agent.
	 */
	@JsonProperty("outcome")
	private String outcome;

	/**
	 * outcomeReasonCode -GCPL Reason code associated with outcome of credit vet
	 * decision provided by the Credit Vet application. Reason codes are populated
	 * for Data Amend (E), Refer (R) and Deline (D) outcomes that provide. This
	 * fields provide additional details on the specific reasons for these outcomes.
	 */
	@JsonProperty("outcomeReasonCode")
	private String outcomeReasonCode;

	/**
	 * Field Double creditClass -GCPL Credit class of credit vet that drives number
	 * of handsets allowed to connect.
	 */
	@JsonProperty("creditClass")
	private Double creditClass;

	/**
	 * Field Double recurringChargeLimit -GCPL This is the threshold value of
	 * recurring charge (tariff) that customer can take offers up to.
	 */
	@JsonProperty("recurringChargeLimit")
	private Double recurringChargeLimit;

	/**
	 * Field Date expiryDateOfLastVet -GCPL Date that indicates the shelf life or
	 * the validity of the latest (or the most recent) credit vet against the
	 * customer party.
	 */
	@JsonProperty("expiryDateOfLastVet")
	private String expiryDateOfLastVet;

	/** Field Double creditLimit -GCPL Credit limit account should adhere to. */
	@JsonProperty("creditLimit")
	private Double creditLimit;

	/**
	 * Field Double shadowLimit -GCPL Limit slightly above credit limit restricts
	 * usage of account.
	 */
	@JsonProperty("shadowLimit")
	private Double shadowLimit;

	/** Field Double maximumNumberOfPostpaidConnectionsAllowed -GCPL. */
	@JsonProperty("maximumNumberOfPostpaidConnectionsAllowed")
	private Double maximumNumberOfPostpaidConnectionsAllowed;

	/** Field Double depositAmount -GCPL Deposit amount required to connect. */
	@JsonProperty("depositAmount")
	private Double depositAmount;

	/**
	 * Field Double depositTimePeriod -GCPL Months before deposit can be returned to
	 * customer.
	 */
	@JsonProperty("depositTimePeriod")
	private Double depositTimePeriod;

	/**
	 * additionalBusinessTerm1 -GCPL This field will be used by CreditVet vendor to
	 * return any additional terms of business in addition to the standard business
	 * terms along with a Credit Vet Result.
	 */
	@JsonProperty("additionalBusinessTerm1")
	private String additionalBusinessTerm1;

	/**
	 * additionalBusinessTerm2 -GCPL This field will be used by CreditVet vendor to
	 * return any additional terms of business in addition to the standard business
	 * terms along with a Credit Vet Result.
	 */
	@JsonProperty("additionalBusinessTerm2")
	private String additionalBusinessTerm2;

	/**
	 * callBarProductId -GCPL Product ID for which the calling bar is specified as
	 * part of the CreditVet result.
	 */
	@JsonProperty("callBarProductId")
	private String callBarProductId;

	/**
	 * Field boolean callBarFlag -GCPL Flag to indicate if the product is barred.
	 */
	@JsonProperty("callBarFlag")
	private Boolean callBarFlag;

	/**
	 * agentNotes -GCPL Notes from the Credit Vet agent against the request. e.g.
	 * TEMPORARY CONNECTION FOR 3 MONTHS
	 */
	@JsonProperty("agentNotes")
	private String agentNotes;

	/**
	 * disableSubscriptionPurchases -GCPL Indicates if the service user is
	 * authorized to perform a specific acivity throug SMS channel. 'true' means not
	 * authorized and 'false' means authorized.
	 */
	@JsonProperty("disableSubscriptionPurchases")
	private String disableSubscriptionPurchases;

	

}
