package com.vf.uk.dal.broadband.entity.customer;

import lombok.Data;

/**
 * The Class PaymentMethod.
 */
@Data
public class PaymentMethod {

	/** The Constant serialVersionUID. */

	/**
	 * paymentMethodCode -GCPL Specifies the Payment Instrument Type. e.g credit
	 * card
	 */
	private String paymentMethodCode;

	/** statusReasonCode -GCPL Reason for the credit card status. */
	private String statusReasonCode;

	/**
	 * statusCode -GCPL Credit card or bank account status LOV: Authorized/Not
	 * Authorized.
	 */
	private String statusCode;

	/**
	 * creditCardNumber -GCPL Card Token number. Generated by PCI For Topup
	 * payment partner, this element is not returned in response
	 */
	private String creditCardNumber;

	/**
	 * expirationMonth -GCPL ExpirationMonth -- Credit card expiration month For
	 * Topup payment partner, this element is not returned in response.
	 */
	private String expirationMonth;

	/**
	 * expirationYear -GCPL ExpirationYear -- Credit card expiration year For
	 * Topup payment partner, this element is not returned in response.
	 */
	private String expirationYear;

	/**
	 * cardHolderBillingAddressPostalCode -GCPL Post code to which the credit
	 * card is registered.
	 */
	private String cardHolderBillingAddressPostalCode;

	/**
	 * cardHolderBillingAddressLineThree -GCPL This is the first full line of
	 * the address where the card is registered to. This includes (where
	 * applicable) the flat/house number and/or the house/building name, and the
	 * street name. Examples: 73B London Road Flat 36, 15 Berkeley Road Osbourne
	 * House, Maple Street
	 */
	private String cardHolderBillingAddressLineThree;

	/** The preferred indicator. */
	private Boolean preferredIndicator;

}
