/*
 * Journey APIs
 * Journey APIs for Authenticated Journeys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.broadband.entity.journey;

import java.util.Objects;

/**
 * FLBBJourneyResponse
 */
public class FLBBJourneyResponse {
	private String journeyId = null;

	/**
	 * @param journeyId
	 * @return
	 */
	public FLBBJourneyResponse journeyId(String journeyId) {
		this.journeyId = journeyId;
		return this;
	}

	/**
	 * Get journeyId
	 * 
	 * @return journeyId
	 **/
	public String getJourneyId() {
		return journeyId;
	}

	public void setJourneyId(String journeyId) {
		this.journeyId = journeyId;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		FLBBJourneyResponse flBBJourneyResponse = (FLBBJourneyResponse) o;
		return Objects.equals(this.journeyId, flBBJourneyResponse.journeyId);
	}

	@Override
	public int hashCode() {
		return Objects.hash(journeyId);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class FLBBJourneyResponse {\n");

		sb.append("    journeyId: ").append(toIndentedString(journeyId)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
