/*
 * Journey APIs
 * Journey APIs for Authenticated Journeys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.broadband.entity.journey;

import java.util.Objects;

/**
 * LineStatus
 */
public class LineStatus {
	private String statusCode = null;

	private String accessLineStatus = null;

	private String gnpStatus = null;

	private String lineOption = null;

	private String technology = null;

	private String lineType = null;

	private String tempStructure = null;

	private String standbyPowerRequired = null;

	private String narrowBandServicesAvailable = null;

	public LineStatus statusCode(String statusCode) {
		this.statusCode = statusCode;
		return this;
	}

	/**
	 * Status of the line LOV - Working, Stopped
	 * 
	 * @return statusCode
	 **/
	public String getStatusCode() {
		return statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	public LineStatus accessLineStatus(String accessLineStatus) {
		this.accessLineStatus = accessLineStatus;
		return this;
	}

	/**
	 * Status of the line (Access Line) LOV - Working, Stopped
	 * 
	 * @return accessLineStatus
	 **/
	public String getAccessLineStatus() {
		return accessLineStatus;
	}

	public void setAccessLineStatus(String accessLineStatus) {
		this.accessLineStatus = accessLineStatus;
	}

	public LineStatus gnpStatus(String gnpStatus) {
		this.gnpStatus = gnpStatus;
		return this;
	}

	/**
	 * The status of the Geographic Number Portability of the number
	 * 
	 * @return gNPStatus
	 **/
	public String getGnpStatus() {
		return gnpStatus;
	}

	public void setGnpStatus(String gnpStatus) {
		this.gnpStatus = gnpStatus;
	}

	public LineStatus lineOption(String lineOption) {
		this.lineOption = lineOption;
		return this;
	}

	/**
	 * Identifies whether existing line can be transferred or a new line is
	 * required LOV - New, Transfer
	 * 
	 * @return lineOption
	 **/
	public String getLineOption() {
		return lineOption;
	}

	public void setLineOption(String lineOption) {
		this.lineOption = lineOption;
	}

	public LineStatus technology(String technology) {
		this.technology = technology;
		return this;
	}

	/**
	 * Identifies a technology associated with the installation
	 * 
	 * @return technology
	 **/
	public String getTechnology() {
		return technology;
	}

	public void setTechnology(String technology) {
		this.technology = technology;
	}

	public LineStatus lineType(String lineType) {
		this.lineType = lineType;
		return this;
	}

	/**
	 * Type of line that is already available LOV - MPF, SMPF, LLU SFI, LLU
	 * SFIM, NTEShiftMPF
	 * 
	 * @return lineType
	 **/
	public String getLineType() {
		return lineType;
	}

	public void setLineType(String lineType) {
		this.lineType = lineType;
	}

	public LineStatus tempStructure(String tempStructure) {
		this.tempStructure = tempStructure;
		return this;
	}

	/**
	 * Is the line requested a temporary structure?
	 * 
	 * @return tempStructure
	 **/
	public String getTempStructure() {
		return tempStructure;
	}

	public void setTempStructure(String tempStructure) {
		this.tempStructure = tempStructure;
	}

	public LineStatus standbyPowerRequired(String standbyPowerRequired) {
		this.standbyPowerRequired = standbyPowerRequired;
		return this;
	}

	/**
	 * Is a standby power required for the line or not?
	 * 
	 * @return standbyPowerRequired
	 **/
	public String getStandbyPowerRequired() {
		return standbyPowerRequired;
	}

	public void setStandbyPowerRequired(String standbyPowerRequired) {
		this.standbyPowerRequired = standbyPowerRequired;
	}

	public LineStatus narrowBandServicesAvailable(String narrowBandServicesAvailable) {
		this.narrowBandServicesAvailable = narrowBandServicesAvailable;
		return this;
	}

	/**
	 * An indicator that specifies whether any Narrow Band Services are
	 * available on the line or not
	 * 
	 * @return narrowBandServicesAvailable
	 **/
	public String getNarrowBandServicesAvailable() {
		return narrowBandServicesAvailable;
	}

	public void setNarrowBandServicesAvailable(String narrowBandServicesAvailable) {
		this.narrowBandServicesAvailable = narrowBandServicesAvailable;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		LineStatus lineStatus = (LineStatus) o;
		return Objects.equals(this.statusCode, lineStatus.statusCode)
				&& Objects.equals(this.accessLineStatus, lineStatus.accessLineStatus)
				&& Objects.equals(this.gnpStatus, lineStatus.gnpStatus)
				&& Objects.equals(this.lineOption, lineStatus.lineOption)
				&& Objects.equals(this.technology, lineStatus.technology)
				&& Objects.equals(this.lineType, lineStatus.lineType)
				&& Objects.equals(this.tempStructure, lineStatus.tempStructure)
				&& Objects.equals(this.standbyPowerRequired, lineStatus.standbyPowerRequired)
				&& Objects.equals(this.narrowBandServicesAvailable, lineStatus.narrowBandServicesAvailable);
	}

	@Override
	public int hashCode() {
		return Objects.hash(statusCode, accessLineStatus, gnpStatus, lineOption, technology, lineType, tempStructure,
				standbyPowerRequired, narrowBandServicesAvailable);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class LineStatus {\n");

		sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
		sb.append("    accessLineStatus: ").append(toIndentedString(accessLineStatus)).append("\n");
		sb.append("    gNPStatus: ").append(toIndentedString(gnpStatus)).append("\n");
		sb.append("    lineOption: ").append(toIndentedString(lineOption)).append("\n");
		sb.append("    technology: ").append(toIndentedString(technology)).append("\n");
		sb.append("    lineType: ").append(toIndentedString(lineType)).append("\n");
		sb.append("    tempStructure: ").append(toIndentedString(tempStructure)).append("\n");
		sb.append("    standbyPowerRequired: ").append(toIndentedString(standbyPowerRequired)).append("\n");
		sb.append("    narrowBandServicesAvailable: ").append(toIndentedString(narrowBandServicesAvailable))
				.append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
