/*
 * Journey APIs
 * Journey APIs for Authenticated Journeys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.broadband.entity.journey;

import java.util.Objects;

/**
 * OfferDetails
 */
public class OfferDetails {
	private String type = null;

	private String code = null;

	public OfferDetails type(String type) {
		this.type = type;
		return this;
	}

	/**
	 * Offer type. Possible values are HARDWARE,SERVICE,INSURANCE etc.
	 * 
	 * @return type
	 **/
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public OfferDetails code(String code) {
		this.code = code;
		return this;
	}

	/**
	 * Offer Id
	 * 
	 * @return code
	 **/
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		OfferDetails offerDetails = (OfferDetails) o;
		return Objects.equals(this.type, offerDetails.type) && Objects.equals(this.code, offerDetails.code);
	}

	@Override
	public int hashCode() {
		return Objects.hash(type, code);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class OfferDetails {\n");

		sb.append("    type: ").append(toIndentedString(type)).append("\n");
		sb.append("    code: ").append(toIndentedString(code)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
