/*
 * Journey APIs
 * Journey APIs for Authenticated Journeys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.broadband.journey.entity;

import lombok.Data;

/**
 * AccessLine.
 */
@Data
public class AccessLine {

	/** The id. */
	private String id = null;

	/** The channel id. */
	private String channelId = null;

}
