/*
 * Journey APIs
 * Journey APIs for Authenticated Journeys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.broadband.journey.entity;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * AuthFLBBJourneyResponse
 */
public class AuthFLBBJourneyResponse {
	private String id = null;

	private String username = null;

	private String contextMSISDN = null;

	private String basketId = null;

	private List<JourneyData> journeyData = null;

	public AuthFLBBJourneyResponse id(String id) {
		this.id = id;
		return this;
	}

	/**
	 * Unique journeyId created to track
	 * 
	 * @return id
	 **/
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public AuthFLBBJourneyResponse username(String username) {
		this.username = username;
		return this;
	}

	/**
	 * IDM Username.
	 * 
	 * @return username
	 **/
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public AuthFLBBJourneyResponse contextMSISDN(String contextMSISDN) {
		this.contextMSISDN = contextMSISDN;
		return this;
	}

	/**
	 * The in-context Service Identifier according to eCare
	 * 
	 * @return contextMSISDN
	 **/
	public String getContextMSISDN() {
		return contextMSISDN;
	}

	public void setContextMSISDN(String contextMSISDN) {
		this.contextMSISDN = contextMSISDN;
	}

	public AuthFLBBJourneyResponse basketId(String basketId) {
		this.basketId = basketId;
		return this;
	}

	/**
	 * Any associated basket Id created for this user
	 * 
	 * @return basketId
	 **/
	public String getBasketId() {
		return basketId;
	}

	public void setBasketId(String basketId) {
		this.basketId = basketId;
	}

	public AuthFLBBJourneyResponse journeyData(List<JourneyData> journeyData) {
		this.journeyData = journeyData;
		return this;
	}

	public AuthFLBBJourneyResponse addJourneyDataItem(JourneyData journeyDataItem) {
		if (this.journeyData == null) {
			this.journeyData = new ArrayList<JourneyData>();
		}
		this.journeyData.add(journeyDataItem);
		return this;
	}

	/**
	 * Get journeyData
	 * 
	 * @return journeyData
	 **/
	public List<JourneyData> getJourneyData() {
		return journeyData;
	}

	public void setJourneyData(List<JourneyData> journeyData) {
		this.journeyData = journeyData;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AuthFLBBJourneyResponse authFLBBJourneyResponse = (AuthFLBBJourneyResponse) o;
		return Objects.equals(this.id, authFLBBJourneyResponse.id)
				&& Objects.equals(this.username, authFLBBJourneyResponse.username)
				&& Objects.equals(this.contextMSISDN, authFLBBJourneyResponse.contextMSISDN)
				&& Objects.equals(this.basketId, authFLBBJourneyResponse.basketId)
				&& Objects.equals(this.journeyData, authFLBBJourneyResponse.journeyData);
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, username, contextMSISDN, basketId, journeyData);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AuthFLBBJourneyResponse {\n");

		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    username: ").append(toIndentedString(username)).append("\n");
		sb.append("    contextMSISDN: ").append(toIndentedString(contextMSISDN)).append("\n");
		sb.append("    basketId: ").append(toIndentedString(basketId)).append("\n");
		sb.append("    journeyData: ").append(toIndentedString(journeyData)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
