/*
 * Journey APIs
 * Journey APIs for Authenticated Journeys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.broadband.journey.entity;

import java.util.Objects;

/**
 * FLBBJourneyDetails.
 */
public class FLBBJourneyDetails {
	
	/** The service point. */
	private ServicePoint servicePoint = null;

	/**
	 * Service point.
	 *
	 * @param servicePoint the service point
	 * @return the FLBB journey details
	 */
	public FLBBJourneyDetails servicePoint(ServicePoint servicePoint) {
		this.servicePoint = servicePoint;
		return this;
	}

	/**
	 * Get servicePoint.
	 *
	 * @return servicePoint
	 */
	public ServicePoint getServicePoint() {
		return servicePoint;
	}

	/**
	 * Sets the service point.
	 *
	 * @param servicePoint the new service point
	 */
	public void setServicePoint(ServicePoint servicePoint) {
		this.servicePoint = servicePoint;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		FLBBJourneyDetails flBBJourneyDetails = (FLBBJourneyDetails) o;
		return Objects.equals(this.servicePoint, flBBJourneyDetails.servicePoint);
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return Objects.hash(servicePoint);
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class FLBBJourneyDetails {\n");

		sb.append("    servicePoint: ").append(toIndentedString(servicePoint)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 *
	 * @param o the o
	 * @return the string
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
