/*
 * Journey APIs
 * Journey APIs for Authenticated Journeys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.broadband.journey.entity;

import java.util.Objects;

/**
 * MiscReference.
 */
public class MiscReference {
	
	/** The service provider name. */
	private String serviceProviderName = null;

	/** The line length. */
	private String lineLength = null;

	/** The classification code. */
	private String classificationCode = null;

	/** The customer agreed date. */
	private String customerAgreedDate = null;

	/** The ready for service date. */
	private String readyForServiceDate = null;

	/** The anfp. */
	private String anfp = null;

	/**
	 * Service provider name.
	 *
	 * @param serviceProviderName the service provider name
	 * @return the misc reference
	 */
	public MiscReference serviceProviderName(String serviceProviderName) {
		this.serviceProviderName = serviceProviderName;
		return this;
	}

	/**
	 * Included when ADSL is already on the line, or when ADSL is being
	 * provided.
	 * 
	 * @return serviceProviderName
	 **/
	public String getServiceProviderName() {
		return serviceProviderName;
	}

	/**
	 * Sets the service provider name.
	 *
	 * @param serviceProviderName the new service provider name
	 */
	public void setServiceProviderName(String serviceProviderName) {
		this.serviceProviderName = serviceProviderName;
	}

	/**
	 * Line length.
	 *
	 * @param lineLength the line length
	 * @return the misc reference
	 */
	public MiscReference lineLength(String lineLength) {
		this.lineLength = lineLength;
		return this;
	}

	/**
	 * Estimate of the line length.
	 *
	 * @return lineLength
	 */
	public String getLineLength() {
		return lineLength;
	}

	/**
	 * Sets the line length.
	 *
	 * @param lineLength the new line length
	 */
	public void setLineLength(String lineLength) {
		this.lineLength = lineLength;
	}

	/**
	 * Classification code.
	 *
	 * @param classificationCode the classification code
	 * @return the misc reference
	 */
	public MiscReference classificationCode(String classificationCode) {
		this.classificationCode = classificationCode;
		return this;
	}

	/**
	 * Get classificationCode.
	 *
	 * @return classificationCode
	 */
	public String getClassificationCode() {
		return classificationCode;
	}

	/**
	 * Sets the classification code.
	 *
	 * @param classificationCode the new classification code
	 */
	public void setClassificationCode(String classificationCode) {
		this.classificationCode = classificationCode;
	}

	/**
	 * Customer agreed date.
	 *
	 * @param customerAgreedDate the customer agreed date
	 * @return the misc reference
	 */
	public MiscReference customerAgreedDate(String customerAgreedDate) {
		this.customerAgreedDate = customerAgreedDate;
		return this;
	}

	/**
	 * Detailed when an ADSL provide or cease is in progress.
	 * 
	 * @return customerAgreedDate
	 **/
	public String getCustomerAgreedDate() {
		return customerAgreedDate;
	}

	/**
	 * Sets the customer agreed date.
	 *
	 * @param customerAgreedDate the new customer agreed date
	 */
	public void setCustomerAgreedDate(String customerAgreedDate) {
		this.customerAgreedDate = customerAgreedDate;
	}

	/**
	 * Ready for service date.
	 *
	 * @param readyForServiceDate the ready for service date
	 * @return the misc reference
	 */
	public MiscReference readyForServiceDate(String readyForServiceDate) {
		this.readyForServiceDate = readyForServiceDate;
		return this;
	}

	/**
	 * If GEA-FTTC is planned, but not yet enabled this field holds the Ready
	 * For Service date.
	 * 
	 * @return readyForServiceDate
	 **/
	public String getReadyForServiceDate() {
		return readyForServiceDate;
	}

	/**
	 * Sets the ready for service date.
	 *
	 * @param readyForServiceDate the new ready for service date
	 */
	public void setReadyForServiceDate(String readyForServiceDate) {
		this.readyForServiceDate = readyForServiceDate;
	}

	/**
	 * Anfp.
	 *
	 * @param anfp the anfp
	 * @return the misc reference
	 */
	public MiscReference anfp(String anfp) {
		this.anfp = anfp;
		return this;
	}

	/**
	 * The Access Network Frequency Plan. The DP category which describes the
	 * length of the line from the cabinet, and thereby providing a view on the
	 * services that are allowed to run.
	 * 
	 * @return anfp
	 **/
	public String getAnfp() {
		return anfp;
	}

	/**
	 * Sets the anfp.
	 *
	 * @param anfp the new anfp
	 */
	public void setAnfp(String anfp) {
		this.anfp = anfp;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		MiscReference miscReference = (MiscReference) o;
		return Objects.equals(this.serviceProviderName, miscReference.serviceProviderName)
				&& Objects.equals(this.lineLength, miscReference.lineLength)
				&& Objects.equals(this.classificationCode, miscReference.classificationCode)
				&& Objects.equals(this.customerAgreedDate, miscReference.customerAgreedDate)
				&& Objects.equals(this.readyForServiceDate, miscReference.readyForServiceDate)
				&& Objects.equals(this.anfp, miscReference.anfp);
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return Objects.hash(serviceProviderName, lineLength, classificationCode, customerAgreedDate,
				readyForServiceDate, anfp);
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class MiscReference {\n");

		sb.append("    serviceProviderName: ").append(toIndentedString(serviceProviderName)).append("\n");
		sb.append("    lineLength: ").append(toIndentedString(lineLength)).append("\n");
		sb.append("    classificationCode: ").append(toIndentedString(classificationCode)).append("\n");
		sb.append("    customerAgreedDate: ").append(toIndentedString(customerAgreedDate)).append("\n");
		sb.append("    readyForServiceDate: ").append(toIndentedString(readyForServiceDate)).append("\n");
		sb.append("    anfp: ").append(toIndentedString(anfp)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 *
	 * @param o the o
	 * @return the string
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
