/*
 * Journey APIs
 * Journey APIs for Authenticated Journeys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.broadband.journey.entity;

import java.util.Objects;

/**
 * PendingOrder.
 */
public class PendingOrder {
	
	/** The completion date. */
	private String completionDate = null;

	/** The type code. */
	private String typeCode = null;

	/** The third party flag. */
	private String thirdPartyFlag = null;

	/**
	 * Completion date.
	 *
	 * @param completionDate the completion date
	 * @return the pending order
	 */
	public PendingOrder completionDate(String completionDate) {
		this.completionDate = completionDate;
		return this;
	}

	/**
	 * The date by which the pending order would be completed.
	 * 
	 * @return completionDate
	 **/
	public String getCompletionDate() {
		return completionDate;
	}

	/**
	 * Sets the completion date.
	 *
	 * @param completionDate the new completion date
	 */
	public void setCompletionDate(String completionDate) {
		this.completionDate = completionDate;
	}

	/**
	 * Type code.
	 *
	 * @param typeCode the type code
	 * @return the pending order
	 */
	public PendingOrder typeCode(String typeCode) {
		this.typeCode = typeCode;
		return this;
	}

	/**
	 * The type of pending order.
	 *
	 * @return typeCode
	 */
	public String getTypeCode() {
		return typeCode;
	}

	/**
	 * Sets the type code.
	 *
	 * @param typeCode the new type code
	 */
	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	/**
	 * Third party flag.
	 *
	 * @param thirdPartyFlag the third party flag
	 * @return the pending order
	 */
	public PendingOrder thirdPartyFlag(String thirdPartyFlag) {
		this.thirdPartyFlag = thirdPartyFlag;
		return this;
	}

	/**
	 * Specifies if the pending order on the line is by a third party (a party
	 * other than the line owner Communications Provider).
	 *
	 * @return thirdPartyFlag
	 */
	public String getThirdPartyFlag() {
		return thirdPartyFlag;
	}

	/**
	 * Sets the third party flag.
	 *
	 * @param thirdPartyFlag the new third party flag
	 */
	public void setThirdPartyFlag(String thirdPartyFlag) {
		this.thirdPartyFlag = thirdPartyFlag;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		PendingOrder pendingOrder = (PendingOrder) o;
		return Objects.equals(this.completionDate, pendingOrder.completionDate)
				&& Objects.equals(this.typeCode, pendingOrder.typeCode)
				&& Objects.equals(this.thirdPartyFlag, pendingOrder.thirdPartyFlag);
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return Objects.hash(completionDate, typeCode, thirdPartyFlag);
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PendingOrder {\n");

		sb.append("    completionDate: ").append(toIndentedString(completionDate)).append("\n");
		sb.append("    typeCode: ").append(toIndentedString(typeCode)).append("\n");
		sb.append("    thirdPartyFlag: ").append(toIndentedString(thirdPartyFlag)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 *
	 * @param o the o
	 * @return the string
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
