/*
 * Journey APIs
 * Journey APIs for Authenticated Journeys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.broadband.journey.entity;

import java.util.Objects;

/**
 * SalesOrderAppointmentRequest.
 */
public class SalesOrderAppointmentRequest {
	
	/** The appointment window. */
	private AppointmentWindow appointmentWindow = null;

	/** The site note. */
	private SiteNote siteNote = null;

	/**
	 * Appointment window.
	 *
	 * @param appointmentWindow the appointment window
	 * @return the sales order appointment request
	 */
	public SalesOrderAppointmentRequest appointmentWindow(AppointmentWindow appointmentWindow) {
		this.appointmentWindow = appointmentWindow;
		return this;
	}

	/**
	 * Get appointmentWindow.
	 *
	 * @return appointmentWindow
	 */
	public AppointmentWindow getAppointmentWindow() {
		return appointmentWindow;
	}

	/**
	 * Sets the appointment window.
	 *
	 * @param appointmentWindow the new appointment window
	 */
	public void setAppointmentWindow(AppointmentWindow appointmentWindow) {
		this.appointmentWindow = appointmentWindow;
	}

	/**
	 * Site note.
	 *
	 * @param siteNote the site note
	 * @return the sales order appointment request
	 */
	public SalesOrderAppointmentRequest siteNote(SiteNote siteNote) {
		this.siteNote = siteNote;
		return this;
	}

	/**
	 * Get siteNote.
	 *
	 * @return siteNote
	 */
	public SiteNote getSiteNote() {
		return siteNote;
	}

	/**
	 * Sets the site note.
	 *
	 * @param siteNote the new site note
	 */
	public void setSiteNote(SiteNote siteNote) {
		this.siteNote = siteNote;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		SalesOrderAppointmentRequest salesOrderAppointmentRequest = (SalesOrderAppointmentRequest) o;
		return Objects.equals(this.appointmentWindow, salesOrderAppointmentRequest.appointmentWindow)
				&& Objects.equals(this.siteNote, salesOrderAppointmentRequest.siteNote);
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return Objects.hash(appointmentWindow, siteNote);
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class SalesOrderAppointmentRequest {\n");

		sb.append("    appointmentWindow: ").append(toIndentedString(appointmentWindow)).append("\n");
		sb.append("    siteNote: ").append(toIndentedString(siteNote)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 *
	 * @param o the o
	 * @return the string
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
