/*
 * Journey APIs
 * Journey APIs for Authenticated Journeys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.broadband.journey.entity;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ServiceReference.
 */
public class ServiceReference {
	
	/** The service lines. */
	private List<ServiceLines> serviceLines = null;

	/**
	 * Service lines.
	 *
	 * @param serviceLines the service lines
	 * @return the service reference
	 */
	public ServiceReference serviceLines(List<ServiceLines> serviceLines) {
		this.serviceLines = serviceLines;
		return this;
	}

	/**
	 * Adds the service lines item.
	 *
	 * @param serviceLinesItem the service lines item
	 * @return the service reference
	 */
	public ServiceReference addServiceLinesItem(ServiceLines serviceLinesItem) {
		if (this.serviceLines == null) {
			this.serviceLines = new ArrayList<>();
		}
		this.serviceLines.add(serviceLinesItem);
		return this;
	}

	/**
	 * Get serviceLines.
	 *
	 * @return serviceLines
	 */
	public List<ServiceLines> getServiceLines() {
		return serviceLines;
	}

	/**
	 * Sets the service lines.
	 *
	 * @param serviceLines the new service lines
	 */
	public void setServiceLines(List<ServiceLines> serviceLines) {
		this.serviceLines = serviceLines;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ServiceReference serviceReference = (ServiceReference) o;
		return Objects.equals(this.serviceLines, serviceReference.serviceLines);
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return Objects.hash(serviceLines);
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ServiceReference {\n");

		sb.append("    serviceLines: ").append(toIndentedString(serviceLines)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 *
	 * @param o the o
	 * @return the string
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
