/*
 * Broadband APIs
 * Braod band API for anonymous and logged in customer
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vf.uk.dal.braodband.entity;

import java.util.Objects;

/**
 * LineIdentification
 */
public class LineIdentification {
  private String fllandlineNumber = null;

  private String typeCode = null;

  private String serviceClassificationCode = null;

  private String moveFromPostCode = null;

  private InstallationAddress installationAddress = null;

  public LineIdentification fllandlineNumber(String fllandlineNumber) {
    this.fllandlineNumber = fllandlineNumber;
    return this;
  }

   /**
   * The directory number currently associated with the copper pair
   * @return fllandlineNumber
  **/
  public String getFllandlineNumber() {
    return fllandlineNumber;
  }

  public void setFllandlineNumber(String fllandlineNumber) {
    this.fllandlineNumber = fllandlineNumber;
  }

  public LineIdentification typeCode(String typeCode) {
    this.typeCode = typeCode;
    return this;
  }

   /**
   * Flag that identifies the type of Business Customer
   * @return typeCode
  **/
  public String getTypeCode() {
    return typeCode;
  }

  public void setTypeCode(String typeCode) {
    this.typeCode = typeCode;
  }

  public LineIdentification serviceClassificationCode(String serviceClassificationCode) {
    this.serviceClassificationCode = serviceClassificationCode;
    return this;
  }

   /**
   * Represents the type of Business service to query for service availability. This is optional field
   * @return serviceClassificationCode
  **/
  public String getServiceClassificationCode() {
    return serviceClassificationCode;
  }

  public void setServiceClassificationCode(String serviceClassificationCode) {
    this.serviceClassificationCode = serviceClassificationCode;
  }

  public LineIdentification moveFromPostCode(String moveFromPostCode) {
    this.moveFromPostCode = moveFromPostCode;
    return this;
  }

   /**
   * Specifies the post code from which the prospective customer is willing to move
   * @return moveFromPostCode
  **/
  public String getMoveFromPostCode() {
    return moveFromPostCode;
  }

  public void setMoveFromPostCode(String moveFromPostCode) {
    this.moveFromPostCode = moveFromPostCode;
  }

  public LineIdentification installationAddress(InstallationAddress installationAddress) {
    this.installationAddress = installationAddress;
    return this;
  }

   /**
   * Get installationAddress
   * @return installationAddress
  **/
  public InstallationAddress getInstallationAddress() {
    return installationAddress;
  }

  public void setInstallationAddress(InstallationAddress installationAddress) {
    this.installationAddress = installationAddress;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LineIdentification lineIdentification = (LineIdentification) o;
    return Objects.equals(this.fllandlineNumber, lineIdentification.fllandlineNumber) &&
        Objects.equals(this.typeCode, lineIdentification.typeCode) &&
        Objects.equals(this.serviceClassificationCode, lineIdentification.serviceClassificationCode) &&
        Objects.equals(this.moveFromPostCode, lineIdentification.moveFromPostCode) &&
        Objects.equals(this.installationAddress, lineIdentification.installationAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fllandlineNumber, typeCode, serviceClassificationCode, moveFromPostCode, installationAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LineIdentification {\n");
    
    sb.append("    fllandlineNumber: ").append(toIndentedString(fllandlineNumber)).append("\n");
    sb.append("    typeCode: ").append(toIndentedString(typeCode)).append("\n");
    sb.append("    serviceClassificationCode: ").append(toIndentedString(serviceClassificationCode)).append("\n");
    sb.append("    moveFromPostCode: ").append(toIndentedString(moveFromPostCode)).append("\n");
    sb.append("    installationAddress: ").append(toIndentedString(installationAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

