/*
 * Broadband APIs
 * Braod band API for anonymous and logged in customer
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.braodband.entity;

import java.util.Objects;

/**
 * LineRef
 */
public class LineRef {
	private LineIdentification lineIdentification = null;

	public LineRef lineIdentification(LineIdentification lineIdentification) {
		this.lineIdentification = lineIdentification;
		return this;
	}

	/**
	 * Get lineIdentification
	 * 
	 * @return lineIdentification
	 **/
	public LineIdentification getLineIdentification() {
		return lineIdentification;
	}

	public void setLineIdentification(LineIdentification lineIdentification) {
		this.lineIdentification = lineIdentification;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		LineRef lineRef = (LineRef) o;
		return Objects.equals(this.lineIdentification, lineRef.lineIdentification);
	}

	@Override
	public int hashCode() {
		return Objects.hash(lineIdentification);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class LineRef {\n");

		sb.append("    lineIdentification: ").append(toIndentedString(lineIdentification)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
