- ParameterKey: Environment
  ParameterValue: "${RELEASE_ENVIRONMENTNAME}"
- ParameterKey: Version
  ParameterValue: "${VERSION}"
- ParameterKey: ContextPath
  ParameterValue: "${CONTEXTPATH}"
- ParameterKey: EcrLocation
  ParameterValue: "${ECRLOCATION}"
- ParameterKey: BuildName
  ParameterValue: "${BUILD_DEFINITIONNAME}"
- ParameterKey: BuildID
  ParameterValue: "${BUILD_BUILDID}"
- ParameterKey: Priority
  ParameterValue: "${PRIORITY}"
- ParameterKey: MaxCapacity
  ParameterValue: "${MAXCAPACITY}"
- ParameterKey: MinCapacity
  ParameterValue: "${MINCAPACITY}"
- ParameterKey: DesiredCount
  ParameterValue: "${DESIREDCOUNT}"
- ParameterKey: Cpu
  ParameterValue: "${CPU}"
- ParameterKey: Memory
  ParameterValue: "${MEMORY}"
- ParameterKey: MemoryReservation
  ParameterValue: "${MEMORYRESERVATION}"
- ParameterKey: HostName
  ParameterValue: "${HOSTNAME}"
- ParameterKey: AppDPort
  ParameterValue: "${APPDPORT}"
- ParameterKey: AppDKey
  ParameterValue: "${APPDKEY}"
- ParameterKey: AppDFlag
  ParameterValue: "${APPDFLAG}"
- ParameterKey: AppDEnv
  ParameterValue: "${APPDENV}"
- ParameterKey: DdogFlag
  ParameterValue: "${DDOGFLAG}"
- ParameterKey: XMS
  ParameterValue: "${XMS}"
- ParameterKey: XMX
  ParameterValue: "${XMX}"
- ParameterKey: JtcLocation
  ParameterValue: "${JTCLOCATION}"
- ParameterKey: JtcFilename
  ParameterValue: "${JTCFILENAME}"
- ParameterKey: HealthyThresholdCount
  ParameterValue: "${HealthyThresholdCount}"
- ParameterKey: UnhealthyThresholdCount
  ParameterValue: "${UnhealthyThresholdCount}"
- ParameterKey: HealthCheckTimeoutSeconds
  ParameterValue: "${HealthCheckTimeoutSeconds}"
- ParameterKey: HealthCheckIntervalSeconds
  ParameterValue: "${HealthCheckIntervalSeconds}"
- ParameterKey: springredishost
  ParameterValue: "${SPRINGREDISHOST}"
- ParameterKey: springredispassword
  ParameterValue: "${SPRINGREDISPASSWORD}"
- ParameterKey: springredisport
  ParameterValue: "${SPRINGREDISPORT}"
- ParameterKey: springredistimeout
  ParameterValue: "${SPRINGREDISTIMEOUT}"
- ParameterKey: springredisttl
  ParameterValue: "${SPRINGREDISTTL}"
- ParameterKey: springredisclusterenabled
  ParameterValue: "${SPRINGREDISCLUSTERENABLED}"
- ParameterKey: icpconfigjdbcUrl
  ParameterValue: "${ICPCONFIGJDBCURL}"
- ParameterKey: icpconfigjdbcUserName
  ParameterValue: "${ICPCONFIGJDBCUSERNAME}"
- ParameterKey: icpconfigjdbcUserPwd
  ParameterValue: "${ICPCONFIGJDBCUSERPWD}"
- ParameterKey: Domain
  ParameterValue: "${DOMAIN}"
- ParameterKey: ListenerArn
  ParameterValue: "${LISTENERARN}"
- ParameterKey: ClusterName
  ParameterValue: "${CLUSTERNAME}"
- ParameterKey: VpcId
  ParameterValue: "${VPCID}"
- ParameterKey: ScalableTargetRoleArn
  ParameterValue: "${SCALABLETARGETROLEARN}"
- ParameterKey: ServiceSchedulerRoleArn
  ParameterValue: "${SERVICESCHEDULERROLEARN}"
- ParameterKey: VPCName
  ParameterValue: "${VPCNAME}"
