/*
 * Journey APIs
 * Journey APIs for Authenticated Journeys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.broadband.cache.repository.entity;

import java.io.Serializable;

import org.springframework.data.annotation.Id;
import org.springframework.data.redis.core.RedisHash;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;

/**
 * FLBBJourneyRequest.
 */
@Data
@RedisHash
public class Broadband implements Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1511608100037673295L;

	/** The service point. */
	@JsonProperty("servicePoint")
	private ServicePoint servicePoint = null;

	/** The sales order appointment. */
	@JsonProperty("salesOrderAppointment")
	private BroadbandSalesOrderAppointment salesOrderAppointment;

	/** The line details. */
	@JsonProperty("lineDetails")
	private LineDetails lineDetails;

	/** The engineering visit charge. */
	@JsonProperty("engineeringVisitCharge")
	private PriceForHardware engineeringVisitCharge = null;

	/** The broad band id. */
	@JsonProperty("broadBandId")
	@Id
	private String broadBandId = null;

	/** The journey id. */
	@JsonProperty("journeyId")
	private String journeyId = null;

	/** The basket id. */
	@JsonProperty("basketId")
	private String basketId = null;

	/** The basket info. */
	@JsonProperty("basketInfo")
	private BasketInfo basketInfo;
	
	@JsonProperty("userDetails")
	private UserDetails userDetails = null;

	/** The category preference. */
	@JsonProperty("categoryPreference")
	private String categoryPreference = null;
	
	/** The isAffiliate flag. */
	@JsonProperty("isAffiliate")
	private Boolean isAffiliate = null;

}
