/*
 * Journey APIs
 * Journey APIs for Authenticated Journeys
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.broadband.cache.repository.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;

/**
 * ServiceLine
 */
@Data
public class ServiceLine implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -7218387192057680974L;

	@JsonProperty("itemReference")
	private ItemReference itemReference = null;

	@JsonProperty("lineSpeeds")
	private LineSpeeds lineSpeeds = null;

	@JsonProperty("miscRefernce")
	private MiscReference miscRefernce = null;

	@JsonProperty("serviceLineTreatments")
	private List<ServiceLineTreatment> serviceLineTreatments = new ArrayList<>();

}
