/*
 * Pricing APIs
 * Bundle API service operations
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.broadband.entity;

import java.util.ArrayList;
import java.util.List;

import org.springframework.hateoas.ResourceSupport;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;

/**
 * MerchandisingPromotion.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-27T07:05:02.425Z")
@Data
public class MerchandisingPromotion extends ResourceSupport{

	/** The tag. */
	@JsonProperty("tag")
	private String tag = null;

	/** The label. */
	@JsonProperty("label")
	private String label = null;

	/** The description. */
	@JsonProperty("description")
	private String description = null;

	/** The discount id. */
	@JsonProperty("discountId")
	private String discountId = null;

	/** The mp type. */
	@JsonProperty("mpType")
	private String mpType = null;

	/** The price established label. */
	@JsonProperty("priceEstablishedLabel")
	private String priceEstablishedLabel = null;

	/** The priority. */
	@JsonProperty("priority")
	private Integer priority = null;

	/** The package type. */
	@JsonProperty("packageType")
	private List<String> packageType = new ArrayList<>();

	/** The package type. */
	@JsonProperty("footNotes")
	private List<String> footNotes = new ArrayList<>();

	/** The promotion media. */
	@JsonProperty("promotionMedia")
	private String promotionMedia = null;

}
