/*
 * Broadband APIs
 * Braod band API for anonymous and logged in customer
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.broadband.entity;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * AvailabilityCheckRequest
 */
public class AvailabilityCheckRequest {
	private LineRef lineRef = null;

	private String journeyId = null;
	
	private List<String> classificationCode = new ArrayList<>();

	public AvailabilityCheckRequest lineRef(LineRef lineRef) {
		this.lineRef = lineRef;
		return this;
	}

	/**
	 * Get lineRef
	 * 
	 * @return lineRef
	 **/
	public LineRef getLineRef() {
		return lineRef;
	}

	public void setLineRef(LineRef lineRef) {
		this.lineRef = lineRef;
	}

	public AvailabilityCheckRequest journeyId(String journeyId) {
		this.journeyId = journeyId;
		return this;
	}

	/**
	 * Existing journey id, for logged in customer journey id will not be null
	 * else null
	 * 
	 * @return journeyId
	 **/
	public String getJourneyId() {
		return journeyId;
	}

	public void setJourneyId(String journeyId) {
		this.journeyId = journeyId;
	}

	public List<String> getClassificationCode() {
		return classificationCode;
	}

	public void setClassificationCode(List<String> classificationCode) {
		this.classificationCode = classificationCode;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AvailabilityCheckRequest availabilityCheckRequest = (AvailabilityCheckRequest) o;
		return Objects.equals(this.lineRef, availabilityCheckRequest.lineRef)
				&& Objects.equals(this.journeyId, availabilityCheckRequest.journeyId);
	}

	@Override
	public int hashCode() {
		return Objects.hash(lineRef, journeyId);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AvailabilityCheckRequest {\n");

		sb.append("    lineRef: ").append(toIndentedString(lineRef)).append("\n");
		sb.append("    journeyId: ").append(toIndentedString(journeyId)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
