/*
 * Basket APIs
 * Basket API service specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vf.uk.dal.broadband.basket.entity;

/**
 * AddDevice
 */

public class AddDevice {

  private String action = null;

 
  private String skuId = null;


   /**
   * Expected list is ADD/REMOVE/MODIFY
   * @return action
  **/
  
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }



   /**
   * Id of the device as given in the product catalogue
   * @return skuId
  **/
  
  public String getSkuId() {
    return skuId;
  }

  public void setSkuId(String skuId) {
    this.skuId = skuId;
  }

}

