/*
 * Basket APIs
 * Basket API service specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vf.uk.dal.broadband.basket.entity;

import java.util.ArrayList;
import java.util.List;

/**
 * CreateBasketResponse
 */

public class CreateBasketResponse {
  
  private String basketId = null;

  
  private List<String> packages = new ArrayList<>();


   /**
   * Unique Id of the basket that was created
   * @return basketId
  **/
  
  public String getBasketId() {
    return basketId;
  }

  public void setBasketId(String basketId) {
    this.basketId = basketId;
  }



   /**
   * Get packages
   * @return packages
  **/
  
  public List<String> getPackages() {
    return packages;
  }

  public void setPackages(List<String> packages) {
    this.packages = packages;
  }
  
}

