/*
 * Basket APIs
 * Basket API service specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vf.uk.dal.broadband.basket.entity;

/**
 * DependentPackage
 */

public class DependentPackage {
  
  private String dependentPackageId = null;

  

   /**
   * package Id of the related package 
   * @return dependentPackageId
  **/
  
  public String getDependentPackageId() {
    return dependentPackageId;
  }

  public void setDependentPackageId(String dependentPackageId) {
    this.dependentPackageId = dependentPackageId;
  }

  
}

