/*
 * Basket APIs
 * Basket API service specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vf.uk.dal.broadband.basket.entity;

/**
 * DiscountPrice
 */

public class DiscountPrice {
 
  private String type = null;

  
  private String value = null;



   /**
   * Discount type - \"PERCENTAGE\" or \"GBP\"
   * @return type
  **/
  
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }



   /**
   * Discount value
   * @return value
  **/
  
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  
}

