/*
 * Basket APIs
 * Basket API service specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vf.uk.dal.broadband.basket.entity;

/**
 * RelatedTo
 */

public class RelatedTo {
 
  private String productLineId = null;

  
  private String skuId = null;

 
  private String productClass = null;

 
  private String relationType = null;

 

   /**
   * Product line Id of a related product as available in this basket
   * @return productLineId
  **/
  
  public String getProductLineId() {
    return productLineId;
  }

  public void setProductLineId(String productLineId) {
    this.productLineId = productLineId;
  }



   /**
   * SKU Id of a related product or bundle
   * @return skuId
  **/
  
  public String getSkuId() {
    return skuId;
  }

  public void setSkuId(String skuId) {
    this.skuId = skuId;
  }

 

   /**
   * Product class of the related product
   * @return productClass
  **/
  
  public String getProductClass() {
    return productClass;
  }

  public void setProductClass(String productClass) {
    this.productClass = productClass;
  }



   /**
   * Relationship type - TBD
   * @return relationType
  **/
  
  public String getRelationType() {
    return relationType;
  }

  public void setRelationType(String relationType) {
    this.relationType = relationType;
  }


  
}

