/*
 * Basket APIs
 * Basket API service specification
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vf.uk.dal.broadband.basket.entity;

/**
 * UpdateService
 */
public class UpdateService {
  private String productLineId = null;

  private String action = null;

  private String skuId = null;

 

   /**
   * Unique id for this line item of the package. This field would be populated only if an existing device in the package is to be modified.
   * @return productLineId
  **/
  public String getProductLineId() {
    return productLineId;
  }

  public void setProductLineId(String productLineId) {
    this.productLineId = productLineId;
  }

  

   /**
   * Expected list is ADD/REMOVE/MODIFY
   * @return action
  **/
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

 

   /**
   * Id of the device as given in the product catalogue
   * @return skuId
  **/
  public String getSkuId() {
    return skuId;
  }

  public void setSkuId(String skuId) {
    this.skuId = skuId;
  }

  
}

