/*
 * Basket APIs
 * Basket API service specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vf.uk.dal.broadband.basket.entity;

/**
 * UpdateBasketResponse
 */

public class UpdateBasketResponse {
 
  private String basketId = null;

 

   /**
   * Unique Id of the basket that was updated
   * @return basketId
  **/
  
  public String getBasketId() {
    return basketId;
  }

  public void setBasketId(String basketId) {
    this.basketId = basketId;
  }

  
}

